parameters:
    acme_blog.document.page.class: 'Acme\BlogBundle\Document\Page'

services:
    acme_blog.page.repository:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.odm.mongodb.document_manager, getRepository]
        arguments:
            - "%acme_blog.document.page.class%"
        public: false

#    acme_blog.page.handler:
#        class: Acme\BlogBundle\Handler\PageHandler
#        arguments: ["@=service('doctrine_mongodb').getRepository('AcmeBlogBundle:Page')"]

    acme_blog.page.handler:
        class: Acme\BlogBundle\Handler\PageHandler
#        autowiring_types: Acme\BlogBundle\Handler\PageHandlerInterface
        arguments:
            - "@acme_blog.page.repository"
            - "@doctrine.odm.mongodb.document_manager"
            - "@form.factory"
            - "%acme_blog.document.page.class%"


#    acme_blog.page.controller:
#        class: Acme\BlogBundle\Controller\PageController
#        arguments: ["@acme_blog.page.handler"]
