parameters:
    acme_blog.document.page.class: 'Acme\BlogBundle\Document\Page'

services:
    acme_blog.page.repository:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.odm.mongodb.document_manager, getRepository]
        arguments:
            - "%acme_blog.document.page.class%"
        public: false
